# Generated by Django 2.1.3 on 2019-02-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_text', models.CharField(max_length=500)),
                ('sub_syl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
            ],
        ),
    ]
