# Generated by Django 2.1.3 on 2019-02-02 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20190202_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_today',
            name='date_today',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
